# https://canonical-charm-refresh.readthedocs-hosted.com/latest/refresh-versions-toml/

charm_major = 1
workload = "8.0.28"

[snap]
name = "charmed-mongodb"

[snap.revisions]
# amd64
x86_64 = "320"
# arm64
aarch64 = "319"
